"""empty message

Revision ID: 9170fc90f1be
Revises: a3b745f1a7d7
Create Date: 2020-07-07 13:39:09.144214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9170fc90f1be'
down_revision = 'a3b745f1a7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_collection_description_key', 'recipe_collection', type_='unique')
    op.drop_column('recipe_collection', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_collection', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('recipe_collection_description_key', 'recipe_collection', ['description'])
    # ### end Alembic commands ###
