"""empty message

Revision ID: aa10b3ae9246
Revises: 9170fc90f1be
Create Date: 2020-07-07 13:39:31.938474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa10b3ae9246'
down_revision = '9170fc90f1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_collection', sa.Column('description', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'recipe_collection', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_collection', type_='unique')
    op.drop_column('recipe_collection', 'description')
    # ### end Alembic commands ###
