"""empty message

Revision ID: b93ed4443d53
Revises: a21275509a07
Create Date: 2020-07-07 13:34:18.842331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b93ed4443d53'
down_revision = 'a21275509a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('ingredients', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('instructions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('recipe_collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_collection_id'], ['recipe_collection.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_table('recipes')
    op.drop_table('recipe_collections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_collections',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('recipe_collections_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='recipe_collections_pkey'),
    sa.UniqueConstraint('title', name='recipe_collections_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('recipes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('ingredients', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('instructions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('recipe_collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipe_collection_id'], ['recipe_collections.id'], name='recipes_recipe_collection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipes_pkey'),
    sa.UniqueConstraint('title', name='recipes_title_key')
    )
    op.drop_table('recipe')
    op.drop_table('recipe_collection')
    # ### end Alembic commands ###
