"""empty message

Revision ID: a21275509a07
Revises: 480b53bd1c9a
Create Date: 2020-07-07 13:04:03.709920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21275509a07'
down_revision = '480b53bd1c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('recipe_collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'recipe_collections', ['recipe_collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'recipe_collection_id')
    # ### end Alembic commands ###
