"""empty message

Revision ID: a3b745f1a7d7
Revises: b93ed4443d53
Create Date: 2020-07-07 13:36:17.684911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b745f1a7d7'
down_revision = 'b93ed4443d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_collection', sa.Column('description', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'recipe_collection', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe_collection', type_='unique')
    op.drop_column('recipe_collection', 'description')
    # ### end Alembic commands ###
