"""empty message

Revision ID: bb3fb8a4b766
Revises: f518602bc986
Create Date: 2020-07-07 13:01:55.415066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3fb8a4b766'
down_revision = 'f518602bc986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('recipe_collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'recipe_collections', ['recipe_collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'recipe_collection_id')
    # ### end Alembic commands ###
