"""empty message

Revision ID: f518602bc986
Revises: d6521a767e13
Create Date: 2020-07-07 13:00:50.274559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f518602bc986'
down_revision = 'd6521a767e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipes_recipe_collection_id_fkey', 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'recipe_collection_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('recipe_collection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('recipes_recipe_collection_id_fkey', 'recipes', 'recipe_collections', ['recipe_collection_id'], ['id'])
    # ### end Alembic commands ###
